name = "Mongoose"
uuid = "494b707d-6180-4d60-8018-fdbee1ff8085"
authors = ["Abraham Jaimes"]
version = "0.2.1"

[deps]
Mongoose_jll = "0a8a3f5b-4c0e-5906-8e29-5b3fee15539c"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
